CORES = fceumm gambatte gpsp pcsx_rearmed picodrive snes9x2005_plus
CORES += beetle-pce-fast beetle-vb fake-08 mednafen_supafaust mgba pokemini fbneo mame2003-plus prboom
CORES += neocd a5200 a7800 a2600 dosbox tyrquake wonderswan puae beetle_ngp desmume2015 #easyrpg #scummvm bmp2png puae

###############################

# optional core vars
# *_REPO=
# *_HASH=
# *_CORE=
# *_FLAGS=
# *_MAKEFILE=
# *_BUILD_PATH=

beetle_ngp_REPO = https://github.com/libretro/beetle-ngp-libretro.git
beetle_ngp_CORE = mednafen_ngp_libretro.so

wonderswan_REPO = https://github.com/libretro/beetle-wswan-libretro.git
wonderswan_CORE = mednafen_wswan_libretro.so

tyrquake_REPO = https://github.com/libretro/tyrquake
tyrquake_CORE = tyrquake_libretro.so

easyrpg_REPO = https://github.com/EasyRPG/Player
easyrpg_CORE = easyrpg_libretro.so

dosbox_REPO = https://github.com/libretro/dosbox-pure.git
dosbox_CORE = dosbox_libretro.so

a2600_REPO = https://github.com/libretro/stella2014-libretro
a2600_CORE = stella2014_libretro.so

a5200_CORE = a5200_libretro.so

a7800_CORE = prosystem_libretro.so
a7800_REPO = https://github.com/libretro/prosystem-libretro

beetle-pce-fast_REPO = https://github.com/libretro/beetle-pce-fast-libretro
beetle-pce-fast_CORE = mednafen_pce_fast_libretro.so

beetle-vb_REPO = https://github.com/libretro/beetle-vb-libretro
beetle-vb_CORE = mednafen_vb_libretro.so

fake-08_REPO = https://github.com/jtothebell/fake-08
fake-08_CORE = fake08_libretro.so
fake-08_BUILD_PATH = fake-08/platform/libretro

fceumm_REPO = https://github.com/libretro/libretro-fceumm

gambatte_REPO = https://github.com/libretro/gambatte-libretro

mednafen_supafaust_REPO = https://github.com/libretro/supafaust


#pcsx_rearmed_REPO = https://github.com/KMFDManic/pcsx_rearmed
pcsx_rearmed_MAKEFILE = Makefile.libretro
#pcsx_rearmed_HASH = 1fec8a9

picodrive_REPO = https://github.com/irixxxx/picodrive
picodrive_MAKEFILE = Makefile.libretro
#picodrive_HASH = c5d8fe3

pokemini_REPO = https://github.com/libretro/PokeMini
pokemini_MAKEFILE = Makefile.libretro

snes9x2005_plus_REPO = https://github.com/libretro/snes9x2005
snes9x2005_plus_FLAGS = USE_BLARGG_APU=1

mame2003-plus_REPO = https://github.com/libretro/mame2003-plus-libretro
mame2003-plus_CORE = mame2003_plus_libretro.so

fbneo_REPO = https://github.com/libretro/fbneo
fbneo_CORE = fbneo_libretro.so
#same version as garlicos
#fbneo_HASH = db9f7e9
fbneo_BUILD_PATH = fbneo/src/burner/libretro

prboom_REPO = https://github.com/libretro/libretro-prboom
prboom_CORE = prboom_libretro.so
#prboom_HASH = 6be5a20

retroarch_REPO = https://github.com/libretro/RetroArch
retroarch_CORE = retroarch
#retroarch 1.14
#retroarch_HASH = ad89b0c
#retroarch 1.15
#retroarch_HASH = 6616b80
#retroarch 1.16
#retroarch_HASH = 6c2cc45
retroarch_MAKEFILE = Makefile.m21

puae_REPO = https://github.com/libretro/libretro-uae
#puae_REPO = https://github.com/KMFDManic/libretro-uae
puae_BR = 2.6.1
puae_CORE = puae2021_libretro.so
#puae_HASH = c68404c

neocd_REPO = https://github.com/libretro/neocd_libretro
neocd_CORE = neocd_libretro.so
#neocd_HASH = 71ebe50

# NDS (desmume2015, RGB565 native -> minarch fast path downsample=0).
# Upstream Makefile.libretro has no m21 branch -> see patches/desmume2015.patch
# (m21 branch with DESMUME_JIT_ARM=1). DESMUME_JIT=0 keeps the x86 backend off;
# ARM32 JIT is selected at runtime via desmume_cpu_mode=jit in default.cfg.
desmume2015_REPO = https://github.com/libretro/desmume2015.git
desmume2015_CORE = desmume2015_libretro.so
desmume2015_MAKEFILE = Makefile.libretro
desmume2015_BUILD_PATH = desmume2015/desmume
desmume2015_FLAGS = DESMUME_JIT=0
#desmume2015_HASH =

bmp2png_REPO = https://github.com/Turro75/bmp2png
bmp2png_CORE = bmp2png
###############################

include ../../all/cores/makefile
